client/components/auth-form.js
client/routes.js
package-lock.json
package.json

Fixed login redirect issue. Now redirects to the Spotify page.

fixed redirect after login

---

package-lock.json
package.json
server/api/albumRouter.js
server/api/artistRouter.js
server/api/featuresRouter.js
server/api/index.js
server/api/playlistRouter.js
server/api/tracksRouter.js
server/auth/spotify-auth.js
server/index.js

Create separate routes for Spotify API

---

client/store/songs.js
server/api/albumRouter.js
server/api/lyricsRouter.js
server/api/tracksRouter.js

Create store for tracks

---

client/components/bubble-chart.js
client/components/react-bubble-chart.js
client/routes.js

D3 Bubble Chart rendering with React. Yay!!!

d3 component is rendering in react

---

client/routes.js
server/api/artistRouter.js
server/api/lyricsRouter.js
server/api/tracksRouter.js

Fix lyrics route#25

---

server/api/tracksRouter.js
server/auth/spotify.js

sends track info

---

server/auth/spotify.js

commented out refresh token

---

client/store/songs.js
server/api/tracksRouter.js

work on backend routes for lyrics

---

server/api/tracksRouter.js

Note: this still needs to be scaled up to incorporate/loop over the full list of tracks received from the Spotify API

Afternoon lyrics data

---

client/components/reactThirdGraph.js
client/components/streamGraph.js
client/routes.js
client/store/index.js
client/store/songs.js
server/api/featuresRouter.js
server/api/tracksRouter.js

added example stream graph
changed some info in the redux store
attempt at seeing info for third graph, not very successful.

Features edits

---

client/components/bubble-chart.js
client/store/songs.js

update songs store to work with lyrics api

---

client/components/react-bubble-chart.js
client/components/reactThirdGraph.js
package-lock.json
package.json
server/api/featuresRouter.js

Complete Router for Track Features

---

package-lock.json
package.json
server/api/tracksRouter.js

Morning route final

---

client/components/bubble-chart.js
client/components/react-bubble-chart.js
client/store/index.js
client/store/songs.js
server/api/tracksRouter.js

Caoimhe rendering bubble chart

---

server/api/tracksRouter.js

fixed try catch error

---

client/components/allGraphPage.js
public/style.css

Added a logo on the navbar, will see if I can do more but the flexbox is tough.

added logo to navbar

---

client/components/error.js
client/components/viewData.js
public/style.css

increase info page font size
added missing bracket to CSS

final changes

---

server/api/albumRouter.js
server/api/artistFreqRouter.js
server/api/artistPopRouter.js
server/api/featuresRouter.js
server/api/tracksRouter.js
server/auth/spotify.js
server/index.js

revised security updates

---

client/components/allGraphPage.js

-facebook logout button added so users can logout of their facebook accounts

added facebook-logout

---

client/components/allGraphPage.js

Centered button text and changes a few classes to className
---

Basic facebook logout

---

client/components/allGraphPage.js
server/auth/spotify.js

Reinstate heroku URI

---

client/components/allGraphPage.js

Change redirect when Logout to Heroku

---

client/components/allGraphPage.js
server/auth/spotify.js

Regular logout

---

client/components/allGraphPage.js

took out timer and async for fb logout

---

client/components/allGraphPage.js

Redirect user to Facebook on Logout

---

client/components/collisionChart.js
public/style.css

added powered by musixmatch logo and link to musixmatch.

adding powered by musixmatch logo

---

client/components/authForm.spec.js

added test
